### ISSUE TITLE
Improving on it to also list, enable and disable assets

### ISSUE THREAD

**Issue by mflage** [burnnat/screenly_ose#1]
Hi!

I was in the process of writing my own implementation of this, but stumbled upon yours in the process of some googling. I noticed, however, that you haven't implemented enabling/disabling of the different assets, along with getting more detailed description of them.

I could probably help out with implementing this, but I'm a bit new to this whole asynchronous stuff, so if you could help me get started with a working example on how to actually use this module, then I could potentially and hopefully provide a PR a little down the road that will have the functions for doing this implemented...

**Comment by burnnat** [comment]
Hi @mflage and thanks for the interest! Truth be told, I'm something of a novice working with asyncio in Python myself but I'm happy to help as much as I can! I started this module to use in a custom [Screenly component](https://github.com/burnnat/media_player.screenly) for [Home Assistant](http://home-assistant.io/), so the only "official" usage is [how I used it in there](https://github.com/burnnat/media_player.screenly/blob/master/custom_components/screenly/media_player.py#L72). There's also some usage [in the tests](https://github.com/burnnat/screenly_ose/blob/master/tests/test_screenly_ose.py#L57) too (using a mock server to handle the API calls).

As far as a simple standalone example I think you should be able to do something like this:
```python
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as websession:
        screenly = Screenly(websession, 'localhost')
        asset = await self._screenly.get_current_asset()
        print(asset)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
(Note, this is just off the top of my head - I haven't actually tried runnig it, so there may be issues.) The documentation for [asyncio](https://docs.python.org/3/library/asyncio.html) and [aiohttp](https://aiohttp.readthedocs.io/en/stable/) may also be helpful. If you're able to get a simple example running, feel free to make a PR adding it to the README.

**Comment by burnnat** [comment]
@mflage I added a verified working example and some API info to the README. I'm closing this issue for now but let me know if there is more information you need.

**Comment by mflage** [comment]
Hehe, and to create a component for Home Assistant was also the same reason why I was looking for a Screenly module myself. So I ended up creating a new project with Requests instead: https://github.com/mflage/pyscreenly . :) I also see that you have implementing switch/enable/disable, so I can probably go ahead and just delete my (first) pip-project.

What I though was looking a bit more at was how to stop Screenly from playing. And also a single playback mode. The API itself has no notion of that. For "stopping", I ended up disabling the current active asset and then "remembering" this in case you want to start Screenly again. The problem with this, however, is if a video or a stream is playing, as this could be playing for potentially a very long time. Do you have any idea how to work around this?
